version: '1.2'
services:
  nest:
    build: .
    ports:
      - 3005:3005
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=nest-test-db
    depends_on:
      - db
      - pma
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:5.7
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'nest-test-db'
    volumes:
      - db-data:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
      MYSQL_ROOT_PASSWORD:
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db-data:
